name: Deploy master
on:
  push:
    branches:
      - Release/#30

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Generate application-prod.yml from secret
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML}}" | base64 --decode > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" | base64 --decode > ./src/main/resources/application-prod.yml

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp build/libs/*.jar deploy/
          cp Procfile deploy/
          if [ -d .ebextensions ]; then cp -r .ebextensions deploy/; fi
          cd deploy
          zip -r ../deploy.zip .
          cd ..

      - name: Set version label
        id: version
        run: echo "VERSION_LABEL=$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ Secrets.EB_ENV_NAME }}
          version_label: ${{ env.VERSION_LABEL }}
          region: ap-northeast-2
          deployment_package: deploy.zip